// Messages that come from the backend as a stable key plus parameters (galton_hoard/messages.py): errors with their hints, the sentences of plans,
// runs and comparisons, and the notices of the Panel. The API keeps an English sentence for assistants; the UI formats these keys itself.
// Each entry is [español, English]; `{name}` placeholders take the parameters. tests/test_client.py checks that every backend key is here, in both
// languages and with the same placeholders.
export const MESSAGES = {
  // ------------------------------------------------------------------ errors (err_) and what to do about them (hint_)
  err_rapida_pick_missing: ["La suite rápida elige un caso que no existe: {suite} / {title}", "rapida picks a case that does not exist: {suite} / {title}"],
  err_no_suite: ["No existe la suite «{ref}».", "No suite '{ref}'."],
  hint_no_suite: ["Consulta las suites en Pruebas.", "List suites with suites_list."],
  err_suite_builtin: ["{name} es una suite incluida y no se puede modificar.", "{name} is a built-in suite and cannot be changed."],
  hint_suite_builtin: ["Duplícala y edita la copia.", "Copy it with suite_duplicate and edit the copy."],
  err_suite_empty: ["La suite {name} no tiene casos.", "Suite {name} has no cases."],
  hint_suite_empty: ["Añade casos o importa algunos.", "Add cases with case_add or import some."],
  err_no_suite_chosen: ["Elige al menos una suite.", "Choose at least one suite."],
  hint_no_suite_chosen: ["Consulta las suites en Pruebas.", "List suites with suites_list."],
  err_no_case: ["No existe el caso {id}.", "No case {id}."],
  hint_no_case: ["Abre la suite para ver sus casos.", "List the cases of a suite with suite_get."],
  err_case_images: ["El caso tiene {n} imagen(es).", "The case has {n} image(s)."],
  err_case_invalid: ["El caso no es válido: {problems}", "The case is not valid: {problems}"],
  err_case_duplicate_title: ["La suite ya tiene un caso con el título «{title}».", "The suite already has a case titled '{title}'."],
  hint_case_duplicate_title: ["Elige otro título o modifica el caso existente.", "Pick another title, or change the existing case with case_update."],
  err_give_case_or_prompt: ["Indica un caso guardado o escribe una pregunta.", "Give a saved `case` or a draft `prompt`."],
  err_shorthand_needs_value: ["La abreviatura de comprobación «{text}» necesita un valor después de los dos puntos.", "The checker shorthand '{text}' needs a value after the colon."],
  hint_shorthand_needs_value: ["Ejemplos: exact:Madrid, contains:uno|dos, number:42, regex:^\\d+$, judge:Es claro y correcto.", "Examples: exact:Madrid, contains:uno|dos, number:42, regex:^\\d+$, judge:Es claro y correcto."],
  err_shorthand_unknown: ["Abreviatura de comprobación desconocida: «{kind}».", "Unknown checker shorthand '{kind}'."],
  hint_shorthand_unknown: ["Usa exact, contains, any, number, choice, regex, math, judge o none.", "Use exact, contains, any, number, choice, regex, math, judge or none."],
  err_not_a_number: ["«{value}» no es un número.", "'{value}' is not a number."],
  err_regex_invalid: ["La expresión regular no es válida: {detail}", "The regular expression is not valid: {detail}"],
  err_row_no_prompt: ["La fila no tiene pregunta (columnas: prompt, pregunta, question, input o text).", "The row has no prompt (columns: prompt, pregunta, question, input or text)."],
  err_checker_json: ["La comprobación no es un JSON válido: {detail}", "The checker is not valid JSON: {detail}"],
  err_weight_number: ["El peso debe ser un número.", "The weight must be a number."],
  err_import_empty: ["No hay nada que importar.", "There is nothing to import."],
  hint_import_empty: ["Pega JSONL (un objeto JSON por línea) o CSV con una fila de cabecera.", "Give JSONL (one JSON object per line) or CSV with a header row."],
  err_json_array_invalid: ["La lista JSON no es válida: {detail}", "The JSON array is not valid: {detail}"],
  err_import_format: ["El formato debe ser auto, jsonl o csv.", "format must be auto, jsonl or csv."],
  err_import_rows: ["Como máximo {max} filas por importación.", "At most {max} rows per import."],
  hint_import_rows: ["Divide el archivo.", "Split the file."],
  err_give_text_or_path: ["Indica el texto o la ruta del archivo, no ambos.", "Give either `text` or `path`."],
  err_import_file_missing: ["No existe el archivo: {path}", "No such file: {path}"],
  hint_import_file_missing: ["Indica la ruta absoluta de un archivo que exista.", "Give the absolute path of an existing file."],
  err_import_file_big: ["Los archivos de importación pueden pesar como máximo 5 MB.", "Import files can be at most 5 MB."],
  err_image_not_absolute: ["La ruta de la imagen debe ser absoluta: {path}", "The image path must be absolute: {path}"],
  err_image_missing: ["No existe la imagen: {path}", "No such image: {path}"],
  err_image_too_large: ["Las imágenes pueden pesar como máximo 10 MB.", "Images can be at most 10 MB."],
  err_image_type: ["{name} no es una imagen PNG, JPEG, WebP ni GIF.", "{name} is not a PNG, JPEG, WebP or GIF image."],
  err_no_model: ["Ningún modelo coincide con «{ref}».", "No model matches '{ref}'."],
  hint_no_model: ["Consulta los modelos en Modelos.", "List models with models_list."],
  err_no_model_refresh: ["Ningún modelo coincide con «{ref}».", "No model matches '{ref}'."],
  hint_no_model_refresh: ["Consulta los modelos o pulsa «Buscar modelos».", "List models with models_list, or run models_refresh."],
  err_no_model_spec: ["Ningún modelo coincide con «{ref}».", "No model matches '{ref}'."],
  hint_no_model_spec: ["Consulta los modelos o indica una especificación como {kind: 'gguf', path: ...}.", "List the models with models_list, or give a spec like {kind: 'gguf', path: ...}."],
  err_no_model_chosen: ["Elige al menos un modelo.", "Choose at least one model."],
  hint_no_model_chosen: ["Consulta los modelos en Modelos.", "List models with models_list."],
  err_model_disabled: ["{name} está desactivado.", "{name} is disabled."],
  hint_model_disabled: ["Actívalo en Modelos.", "Enable it with model_update."],
  err_model_gone: ["{name} ya no está instalado.", "{name} is no longer installed."],
  hint_model_gone: ["Busca modelos de nuevo o elige otro.", "Refresh the models, or pick another."],
  err_model_busy_run: ["{name} se está midiendo ahora mismo.", "{name} is being measured right now."],
  hint_model_busy_run: ["Cancela antes la ejecución.", "Cancel the run first."],
  err_model_file_gone: ["Ya no existe el archivo del modelo: {path}", "The model file is gone: {path}"],
  hint_model_file_gone: ["Busca modelos de nuevo.", "Refresh the models."],
  err_size_unknown: ["Se desconoce el tamaño de {name}.", "The size of {name} is unknown."],
  hint_size_unknown: ["Busca modelos de nuevo o comprueba que el archivo siga existiendo.", "Refresh the models, or check that the file still exists."],
  err_remote_ok_local: ["{name} es un modelo local: remote_ok solo se aplica a puntos remotos.", "{name} is a local model: remote_ok only applies to remote endpoints."],
  err_remote_not_allowed: ["{name} es un punto remoto y no se ha autorizado para medirlo.", "{name} is a remote endpoint and was not enabled for measuring."],
  hint_remote_not_allowed: ["Las llamadas remotas pueden costar dinero y envían las preguntas fuera de este ordenador: autorízalo de forma explícita en Modelos.", "Remote calls can cost money and send prompts off this computer: enable it explicitly with model_update remote_ok=true."],
  err_compare_same_model: ["Elige dos modelos distintos.", "Pick two different models."],
  err_contestant_spec: ["Un participante es un id, un nombre o un objeto de especificación.", "A contestant is an id, a name or a spec object."],
  err_unknown_kind: ["Tipo de participante desconocido: «{kind}».", "Unknown contestant kind '{kind}'."],
  hint_unknown_kind: ["Usa gguf, ollama o server.", "Use gguf, ollama or server."],
  err_gguf_needs_path: ["Un participante gguf necesita la ruta.", "A gguf contestant needs `path`."],
  hint_gguf_needs_path: ["Indica la ruta absoluta del archivo .gguf.", "Give the absolute path of the .gguf file."],
  err_path_not_absolute: ["La ruta debe ser absoluta: {path}", "`path` must be absolute: {path}"],
  hint_path_not_absolute: ["Usa la ruta completa, por ejemplo D:\\modelos\\modelo.gguf.", "Use the full path, for example D:\\models\\model.gguf."],
  err_file_missing: ["No existe el archivo: {path}", "No such file: {path}"],
  hint_file_missing: ["Comprueba la ruta.", "Check the path."],
  err_file_unreadable: ["No se puede abrir {path}: {detail}", "Cannot open {path}: {detail}"],
  hint_file_unreadable: ["Comprueba la ruta y que el archivo se pueda leer.", "Check the path and that the file is readable."],
  err_is_projector: ["{name} es un proyector de visión, no un modelo.", "{name} is a vision projector, not a model."],
  hint_is_projector: ["Indica el archivo del modelo; el proyector va en el campo de proyector.", "Give the model file; the projector goes in `mmproj`."],
  err_no_projector: ["No existe el archivo del proyector: {path}", "No such projector file: {path}"],
  err_ollama_needs_model: ["Un participante de Ollama necesita el nombre del modelo.", "An ollama contestant needs `model`."],
  err_ollama_not_installed: ["El modelo «{model}» de Ollama no está instalado (no hay manifiesto).", "Ollama model '{model}' is not installed (no manifest found)."],
  hint_ollama_not_installed: ["Busca modelos de nuevo o comprueba el nombre con `ollama list`.", "Run models_refresh, or check the name with `ollama list`."],
  err_server_needs_url_model: ["Un participante de servidor necesita la dirección y el modelo.", "A server contestant needs `url` and `model`."],
  err_add_model_args: ["Indica la dirección de un servidor en marcha o la ruta de un archivo .gguf.", "Give either `url` (a running server) or `path` (a .gguf file)."],
  err_url_scheme: ["La dirección debe empezar por http:// o https://.", "`url` must start with http:// or https://."],
  err_offline_no_probe: ["Esta instancia funciona sin red (modo demostración o de pruebas): no se pueden consultar servidores.", "This instance runs offline (demo or test mode): servers cannot be probed."],
  err_server_no_answer_kind: ["{url} no responde como servidor de chat (llama-server y similares) ni como Ollama.", "{url} does not answer as a chat-completions server (llama-server and similar) or as Ollama."],
  hint_server_no_answer_kind: ["Comprueba la dirección y que el servidor esté en marcha.", "Check the address and that the server is running."],
  err_server_pick_model: ["Indica qué modelo usar.", "Say which `model` to use."],
  hint_server_pick_model: ["El servidor ofrece: {options}.", "The server offers: {options}."],
  err_server_lacks_model: ["El servidor no lista «{model}».", "The server does not list '{model}'."],
  hint_server_lacks_model: ["Ofrece: {options}.", "It offers: {options}."],
  err_unknown_api: ["Tipo de API desconocido: «{api}».", "Unknown API kind '{api}'."],
  hint_unknown_api: ["Usa un tipo de API conocido: chat u ollama.", "Use a known API kind: chat or ollama."],
  err_no_vision: ["{name} no tiene visión y el caso lleva una imagen.", "{name} has no vision and the case has an image."],
  hint_no_vision: ["Elige un modelo con visión.", "Pick a model with vision."],
  err_server_no_answer: ["El servidor {url} no responde.", "The server {url} does not answer."],
  hint_server_no_answer: ["Arráncalo o busca modelos de nuevo; puede haber cambiado de puerto.", "Start it, or refresh the models; it may have moved to another port."],
  err_server_busy: ["El servidor {url} siguió ocupado con peticiones de otra persona durante {limit} s, así que la ejecución dejó de esperarlo.", "The server {url} stayed busy with somebody else's requests for {limit} s, so the run stopped waiting for it."],
  hint_server_busy: ["Vuelve a lanzarla más tarde o sube runner.wait_idle_max_s (0 espera sin límite); Galton no compite con tus conversaciones.", "Run it again later, or raise runner.wait_idle_max_s (0 waits for ever); Galton does not compete with your chats."],
  err_server_changed: ["El servidor en {url} sirve ahora {model}; actualiza los modelos.", "The server at {url} now serves {model}; refresh the models."],
  hint_server_changed: ["Esta entrada mide {expected}. Al actualizar los modelos, el que se sirve ahora tiene su propia entrada; esta conserva su historial y vuelve cuando el servidor la sirva de nuevo.", "This entry measures {expected}. models_refresh gives the model that is served now its own entry; this one keeps its history and comes back when the server serves it again."],
  err_server_unverified: ["El servidor en {url} no respondió cuando había que comprobar los últimos {n} resultados, así que no se guardaron.", "The server at {url} did not answer when the last {n} result(s) were to be checked, so they were not stored."],
  hint_server_unverified: ["Arranca el servidor y vuelve a lanzar la medición.", "Start the server and run it again."],
  err_model_not_served: ["{name} no se sirve ahora: el servidor en {url} sirve {model}.", "{name} is not served now: the server at {url} serves {model}."],
  hint_model_not_served: ["Actualiza los modelos, vuelve a arrancar {name} en ese servidor o elige el modelo que se sirve ahora.", "Refresh the models, start {name} on that server again, or pick the model that is served now."],
  err_ollama_not_loaded: ["{name} no está cargado en Ollama y la carga está desactivada.", "{name} is not loaded in Ollama and loading it is switched off."],
  hint_ollama_not_loaded: ["Activa runner.allow_ollama_load o mídelo con llama.cpp (la entrada del mismo modelo basada en archivo).", "Enable runner.allow_ollama_load, or measure it through llama.cpp (the file-based entry of the same model)."],
  err_ollama_no_answer: ["Ollama en {url} no responde.", "Ollama at {url} does not answer."],
  hint_ollama_no_answer: ["Arranca Ollama o busca modelos de nuevo.", "Start Ollama, or refresh the models."],
  err_no_llama_server: ["No se encontró llama-server (se buscó en {where} y en el PATH).", "llama-server was not found (looked for {where} and for llama-server on PATH)."],
  hint_no_llama_server: ["Indica la ruta de llama-server en Ajustes > Ejecución, o mide el modelo en un servidor que ya esté en marcha.", "Set the path of llama-server in Settings > Runner, or run the model on a server that is already up."],
  err_ports_busy: ["Los puertos 8091-8099 están todos en uso.", "Ports 8091-8099 are all in use."],
  hint_ports_busy: ["Detén los procesos llama-server que Galton dejó en marcha (consulta servers.json) o espera a que termine una ejecución.", "Stop the llama-server processes that Galton left running (see servers.json) or wait for a run to end."],
  err_server_start_failed: ["No se pudo arrancar llama-server: {detail}", "Could not start llama-server: {detail}"],
  hint_server_start_failed: ["Comprueba la ruta de llama-server en Ajustes.", "Check the llama-server path in Settings."],
  err_cancelled_loading: ["Cancelado mientras se cargaba el modelo.", "Cancelled while the model was loading."],
  err_server_exited: ["llama-server terminó con el código {exit_code} durante la carga.", "llama-server exited with code {exit_code} while loading."],
  hint_server_exited: ["Últimas líneas del registro: {log_tail}", "Last log lines: {log_tail}"],
  err_server_not_ready: ["llama-server no estuvo listo en {seconds} s.", "llama-server did not become ready within {seconds} s."],
  hint_server_not_ready: ["Últimas líneas del registro: {log_tail}", "Last log lines: {log_tail}"],
  err_no_run: ["No existe la ejecución {id}.", "No run {id}."],
  hint_no_run: ["Consulta las ejecuciones en Ejecutar.", "List runs with run_status."],
  err_run_not_finished: ["La ejecución {id} sigue en estado «{state}».", "Run {id} is still {state}."],
  hint_run_not_finished: ["Cancélala y descártala cuando se haya detenido.", "Cancel it with run_cancel and discard it once it has stopped."],
  err_no_run_contestant: ["No hay ningún participante {contestant} en la ejecución {run}.", "No contestant {contestant} in run {run}."],
  err_no_runs: ["Todavía no hay ejecuciones.", "There are no runs yet."],
  hint_no_runs: ["Inicia una en Ejecutar.", "Start one with run_start."],
  err_run_unknown_settings: ["Ajustes de ejecución desconocidos: {names}.", "Unknown run settings: {names}."],
  hint_run_unknown_settings: ["Conocidos: {options}.", "Known: {options}."],
  err_no_nvidia: ["No se encontró ninguna GPU NVIDIA (nvidia-smi no devolvió inventario).", "No NVIDIA GPU was found (nvidia-smi gave no inventory)."],
  hint_no_nvidia: ["Instala el controlador de NVIDIA o mide el modelo en un servidor que ya esté en marcha (un participante de servidor).", "Install the NVIDIA driver or run the model on a server that is already up (a server contestant)."],
  err_allowed_missing: ["Ninguna de las GPU permitidas ({allowed}) existe en este ordenador.", "None of the allowed GPUs ({allowed}) exists on this computer."],
  hint_allowed_missing: ["Elige las GPU que se pueden usar en Ajustes > GPU.", "Choose the GPUs to use in Settings > GPUs."],
  err_gpu_capacity: ["El modelo necesita unos {need_gb} GB y las GPU permitidas {present} suman {capacity_gb} GB.", "The model needs about {need_gb} GB and the allowed GPUs {present} hold {capacity_gb} GB in total."],
  hint_gpu_capacity: ["Usa una cuantización menor o un contexto más corto, o permite otra GPU en Ajustes (las del dueño están reservadas).", "Use a smaller quantisation or a shorter context, or allow another GPU in Settings (the owner's GPUs are reserved)."],
  err_lease_refused: ["El concentrador de GPU rechazó la reserva: {reason}", "The GPU hub refused the lease: {reason}"],
  hint_lease_refused: ["El modelo no cabe en esa GPU ni estando vacía.", "The model cannot fit on that GPU even when it is empty."],
  err_lease_not_allowed: ["La reserva cayó en la GPU {granted}, que no está en la lista permitida {allowed}.", "The lease landed on GPU {granted}, which is not in the allowed list {allowed}."],
  hint_lease_not_allowed: ["Galton nunca usa una GPU fuera de Ajustes > GPU; no se cargó nada.", "Galton never uses a GPU outside Settings > GPUs; nothing was loaded."],
  err_cancelled_waiting_gpu: ["Cancelado mientras esperaba una GPU.", "Cancelled while waiting for a GPU."],
  err_no_gpu_free: ["Ninguna GPU permitida tiene {need_gb} GB libres.", "No allowed GPU has {need_gb} GB free."],
  hint_no_gpu_free: ["Espera a que termine el otro trabajo, libera memoria o inténtalo más tarde.", "Wait for the other job to finish, free memory, or try again later."],
  err_cpu_no_ram: ["El modelo necesita unos {need_gb} GB de memoria para ir en la CPU y solo hay {free_gb} GB libres.", "The model needs about {need_gb} GB of memory to run on the CPU and only {free_gb} GB are free."],
  hint_cpu_no_ram: ["Cierra otros programas o espera a que haya memoria libre.", "Close other programs, or wait until memory is free."],
  err_no_gpu_free_waited: ["Ninguna GPU permitida tiene {need_gb} GB libres tras esperar.", "No allowed GPU has {need_gb} GB free after waiting."],
  hint_no_gpu_free_waited: ["Espera a que termine el otro trabajo, libera memoria o inténtalo más tarde.", "Wait for the other job to finish, free memory, or try again later."],
  err_gpu_reserved: ["La GPU {gpus} está reservada para el dueño de este ordenador.", "GPU {gpus} is reserved for the owner of this computer."],
  hint_gpu_reserved: ["Repite la acción confirmando solo si el usuario lo ha permitido de forma explícita.", "Repeat the call with confirm_reserved=true only if the user explicitly allowed it."],
  err_setting_bool: ["{setting} debe ser verdadero o falso.", "{setting} must be true or false."],
  err_setting_number: ["{setting} debe ser un número.", "{setting} must be a number."],
  err_setting_range: ["{setting} debe estar entre {low} y {high}.", "{setting} must be between {low} and {high}."],
  err_setting_choice: ["{setting} debe ser uno de estos valores: {options}.", "{setting} must be one of {options}."],
  err_setting_intlist: ["{setting} debe ser una lista de números enteros.", "{setting} must be a list of whole numbers."],
  err_setting_intlist_range: ["{setting}: {number} está fuera de rango.", "{setting}: {number} is out of range."],
  err_setting_object: ["{setting} debe ser un objeto.", "{setting} must be an object."],
  err_setting_unknown_field: ["Campo desconocido {name} en {setting}.", "Unknown field {name} in {setting}."],
  hint_setting_unknown_field: ["Conocidos: {options}.", "Known: {options}."],
  err_setting_field_number: ["{setting}.{name} debe ser un número.", "{setting}.{name} must be a number."],
  err_setting_field_range: ["{setting}.{name} debe estar entre {low} y {high}.", "{setting}.{name} must be between {low} and {high}."],
  err_setting_type: ["Tipo de ajuste no admitido para {setting}.", "Unsupported setting type for {setting}."],
  err_setting_unknown: ["Ajuste desconocido: {setting}.", "Unknown setting {setting}."],
  hint_setting_unknown: ["Conocidos: {options}.", "Known: {options}."],
  err_arena_bad_vote: ["El voto debe ser uno de estos: {options}.", "vote must be one of {options}."],
  err_arena_no_pair: ["No existe el par de la arena {pair}.", "No arena pair {pair}."],
  hint_arena_no_pair: ["Pide un par nuevo en la arena.", "Ask for a pair with arena_next."],
  err_arena_already_voted: ["Ese par ya tiene un voto.", "That pair already has a vote."],
  hint_arena_already_voted: ["Pide un par nuevo en la arena.", "Ask for a new pair with arena_next."],
  err_unknown_category: ["Categoría desconocida: «{category}».", "Unknown category '{category}'."],
  hint_unknown_category: ["Usa una de estas: {options}.", "Use one of: {options}."],
  err_unknown_task_category: ["Categoría de tarea desconocida: «{category}».", "Unknown task category '{category}'."],
  hint_unknown_task_category: ["Usa una de estas: {options}.", "Use one of: {options}."],
  err_nothing_to_publish: ["No hay nada que publicar: ninguna categoría de tareas tiene suficientes casos comprobados.", "There is nothing to publish: no task category has enough checked cases."],
  hint_nothing_to_publish: ["Ejecuta antes las suites con tus modelos; cada categoría necesita al menos routes.min_cases casos comprobados.", "Run suites on your models first (see recommend or run_start); a category needs at least routes.min_cases checked cases."],
  err_confirm_delete: ["Borrar {what} es permanente.", "Deleting {what} is permanent."],
  hint_confirm_delete: ["Repite la acción con confirmación si el usuario lo ha pedido.", "Repeat the call with confirm=true if the user asked for it."],
  err_confirm_discard: ["Descartar {what} quita sus resultados de toda estadística, clasificación, ruta y comparación.", "Discarding {what} removes its results from every statistic, ranking, route and comparison."],
  hint_confirm_discard: ["Repite la acción con confirmación si el usuario lo ha pedido; restaurar la ejecución devuelve los resultados.", "Repeat the call with confirm=true if the user asked for it; run_restore brings them back."],

  // ------------------------------------------------------------------ sentences of plans, runs and comparisons (msg_)
  msg_where_server: ["servidor {url}", "server {url}"],
  msg_where_server_resident: ["servidor {url} (residente)", "server {url} (resident)"],
  msg_where_gpus: ["GPU {gpus}", "GPU {gpus}"],
  msg_where_wait: ["esperaría hueco en las GPU permitidas", "would wait for room on the allowed GPUs"],
  msg_where_cpu: ["CPU (no hay GPU libre)", "CPU (no GPU is free)"],
  msg_where_cpu_forced: ["CPU (elegido en la ejecución)", "CPU (chosen in the run)"],
  msg_runs_on_cpu: ["llama.cpp (propio) en la CPU, {threads} hilos", "llama.cpp (own) on the CPU, {threads} threads"],
  msg_runs_on_own: ["llama.cpp (propio) en la GPU {gpus}", "llama.cpp (own) on GPU {gpus}"],
  msg_runs_on_server: ["llama-server {url}", "llama-server {url}"],
  msg_runs_on_ollama: ["ollama {url}", "ollama {url}"],
  msg_runs_on_ollama_loaded: ["ollama {url} (cargado por Galton)", "ollama {url} (loaded by Galton)"],
  msg_note_vision_dropped: ["{n} caso(s) de visión no se ejecutaron: {name} no tiene visión", "{n} vision case(s) were not run: {name} has no vision"],
  msg_warn_cpu: ["Medido en la CPU ({threads} hilos), no en una GPU: su velocidad no es comparable con la de las GPU", "Measured on the CPU ({threads} threads), not on a GPU: its speed is not comparable with GPU numbers"],
  msg_warn_split: ["repartido entre las GPU {gpus} ({split})", "split across GPUs {gpus} ({split})"],
  msg_warn_ollama_gpu: ["Ollama decide en qué GPU carga el modelo; la reserva solo aparta la memoria", "Ollama decides which GPU it loads the model on; the lease only reserves the memory"],
  msg_warn_spill: ["El {pct} % del modelo está en la RAM del sistema, no en la GPU (las velocidades son menores que con carga completa en GPU)", "{pct} % of the model is in system RAM, not on the GPU (speeds are lower than a full GPU load)"],
  msg_warn_lease_hub: ["El concentrador de GPU no responde; solo se comprobó en local: {detail}", "GPU lease hub not reachable; local check only: {detail}"],
  msg_warn_will_fail: ["{name} fallará: {problem}", "{name} will fail: {problem}"],
  msg_skip_context: ["omitido: contexto ({needed} tokens necesarios, {available} disponibles)", "skipped: context ({needed} tokens needed, {available} available)"],
  msg_chat_timeout: ["tiempo agotado: sin respuesta en {seconds} s", "timeout: no answer within {seconds} s"],
  msg_chat_timeout_detail: ["tiempo agotado: {detail}", "timeout: {detail}"],
  msg_chat_connection: ["error de conexión: {detail}", "connection error: {detail}"],
  msg_chat_rejected: ["el servidor siguió rechazando la petición", "the server kept rejecting the request"],
  msg_chat_error: ["{detail}", "{detail}"],
  msg_internal_error: ["error interno: {detail}", "internal error: {detail}"],
  msg_note_reasoning_retry: ["el servidor rechazó los campos de razonamiento; se repitió sin ellos", "the server rejected the reasoning fields; retried without them"],
  msg_note_tools_in_prompt_server: ["tools_in_prompt: el servidor no admite el campo de herramientas; se describieron en la pregunta", "tools_in_prompt: the server does not take the tools field; they were described in the prompt"],
  msg_note_reasoning_budget_retry: ["la respuesta se cortó mientras el modelo aún razonaba; se volvió a preguntar con {tokens} tokens más", "the answer was cut while the model was still reasoning; asked again with {tokens} more tokens"],
  msg_warn_reasoning_budget: ["Este modelo razona: se suman {tokens} tokens al presupuesto de respuesta de cada caso para que pensar no se coma la respuesta", "This model reasons: {tokens} tokens are added to the answer budget of each case so that its thinking does not use up the answer"],
  msg_note_think_retry: ["el modelo no admite la opción de pensar; se repitió sin ella", "the model does not take the think option; retried without it"],
  msg_note_tools_in_prompt_model: ["tools_in_prompt: el modelo no admite herramientas; se describieron en la pregunta", "tools_in_prompt: the model does not support tools; they were described in the prompt"],
  msg_run_stopped: ["Galton se detuvo mientras esta ejecución estaba en curso.", "Galton was stopped while this run was in progress."],
  msg_rc_interrupted: ["interrumpido", "interrupted"],
  msg_run_all_failed: ["Todos los modelos fallaron; el motivo está en cada modelo, más abajo.", "Every model failed; the reason is on each model below."],
  msg_run_finished: ["la ejecución ya había terminado", "the run had already finished"],
  msg_run_stopping_own: ["deteniendo: se descarta la petición en curso y se para el llama-server que Galton arrancó", "stopping: the request in flight is dropped and the llama-server that Galton started is stopped"],
  msg_run_stopping_shared: ["deteniendo: se descarta la petición en curso; el servidor compartido en {urls} no se toca y sigue funcionando", "stopping: the request in flight is dropped; the shared server at {urls} is not touched and keeps running"],
  msg_run_stopping_both: ["deteniendo: se descarta la petición en curso y se para el llama-server que Galton arrancó; el servidor compartido en {urls} no se toca y sigue funcionando", "stopping: the request in flight is dropped and the llama-server that Galton started is stopped; the shared server at {urls} is not touched and keeps running"],
  msg_run_stopping_none: ["deteniendo: se descarta la petición en curso", "stopping: the request in flight is dropped"],
  msg_warn_results_dropped: ["{n} resultado(s) respondidos desde la última comprobación del servidor no se guardaron", "{n} result(s) answered since the server was last checked were not stored"],
  msg_run_discard_note: ["Sus resultados ya no cuentan en ninguna estadística, clasificación, ruta, comparación ni control de regresiones; la ejecución sigue en el historial. Restaurarla los devuelve.", "Its results no longer count in any statistic, ranking, route, comparison or regression check; the run stays in the history. run_restore brings them back."],
  msg_run_restore_note: ["Sus resultados vuelven a contar.", "Its results count again."],
  msg_run_not_discarded_note: ["la ejecución no estaba descartada", "the run was not discarded"],
  msg_judge_none: ["no hay modelo juez elegido (ajuste judge.contestant)", "no judge model is chosen (setting judge.contestant)"],
  msg_judge_unavailable: ["el juez {name} no está disponible", "the judge {name} is not available"],
  msg_judge_not_started: ["no se pudo arrancar el juez: {reason}", "the judge could not be started: {reason}"],
  msg_cmp_no_shared: ["Los dos modelos no comparten ningún caso comprobado: ejecuta ambos con las mismas suites.", "The two models share no checked case: run both on the same suites."],
  msg_cmp_few_cases: ["Solo hay {n} casos en común (menos de {min}): el veredicto es débil, mide más casos antes de decidir.", "Only {n} cases in common (fewer than {min}): the verdict is weak, measure more cases before deciding."],
  msg_cmp_disagree: ["La prueba de aprobado/suspenso y el bootstrap de la puntuación no coinciden, así que no se afirma ninguna diferencia.", "The pass/fail test and the score bootstrap disagree, so no difference is claimed."],
  msg_board_stale_left_out: ["Los resultados de {names} son de una versión anterior del archivo y se han dejado fuera (usa incluir obsoletos para verlos).", "Results of {names} are for an older version of the file and were left out (pass include_stale to use them)."],
  msg_board_truncated: ["{name}: {n} de {total} resultados en {category} ({pct} %) acabaron sin respuesta porque se agotó el presupuesto de tokens: el presupuesto era demasiado pequeño y la puntuación infravalora al modelo", "{name}: {n} of {total} results in {category} ({pct} %) ended with no answer because the token budget ran out: the budget was too small, so the score understates the model"],
  msg_board_unequal_results: ["{a} tiene {who_a} y {b} tiene {who_b} resultados comprobados en {label}.", "{a} has {who_a} and {b} has {who_b} checked results in {label}."],
  msg_excl_disabled: ["desactivado o ya no instalado", "disabled or no longer installed"],
  msg_excl_adhoc: ["modelo solo de evaluación (consérvalo para poder enrutar hacia él)", "evaluation-only model (keep it to route to it)"],
  msg_excl_remote: ["punto remoto (routes.include_remote está desactivado)", "remote endpoint (routes.include_remote is off)"],
  msg_excl_no_results: ["sin resultados recientes en estas suites", "no recent results on these suites"],
  msg_excl_stale: ["los resultados son de otra versión del modelo", "results are for another version of the model"],
  msg_excl_too_few: ["menos casos comprobados que routes.min_cases", "fewer checked cases than routes.min_cases"],
  msg_excl_too_slow: ["más lento que routes.min_tok_s", "slower than routes.min_tok_s"],
  msg_excl_too_big: ["necesita más memoria que routes.max_vram_gb", "needs more memory than routes.max_vram_gb"],
  msg_not_chat_no_template: ["Este servidor no tiene plantilla de chat: no es un modelo de conversación.", "This server has no chat template: it is not a chat model."],
  msg_not_chat_failed: ["El servidor respondió con un error ({status}) a la prueba de chat: no es un modelo de conversación.", "The server answered the chat probe with an error ({status}): it is not a chat model."],
  msg_case_no_checker: ["Este caso no tiene comprobación: se guardan sus respuestas (y sirven para la arena) pero no cuenta para ninguna puntuación.", "This case has no checker: its answers are recorded (and usable in the arena) but it does not count towards any score."],
  msg_case_judge_pending: ["Este caso lo califica el modelo juez (ajuste judge.contestant); hasta que se elija uno, sus resultados quedan pendientes.", "This case is graded by the judge model (setting judge.contestant); until one is chosen its results stay pending."],
  msg_model_remote_note: ["Es un punto remoto: no se llamará hasta que se autorice (puede costar dinero y envía las preguntas fuera de este ordenador).", "This is a remote endpoint: it will not be called until remote_ok is enabled (it can cost money and sends prompts off this computer)."],
  msg_case_results_deleted: ["Se borraron {n} resultado(s) anteriores de este caso.", "{n} earlier result(s) of this case were deleted."],
  msg_case_results_old: ["{n} resultado(s) anteriores de este caso miden la versión antigua. Pide olvidar los resultados para borrarlos.", "{n} earlier result(s) of this case measured the old version. Pass forget_results=true to delete them."],
  msg_label_watch: ["vigilancia: {name}", "watch: {name}"],
  msg_label_measure_new: ["Medir lo nuevo ({n})", "Measure what is new ({n})"],
  msg_measure_new_none: ["Todos los modelos activos ya tienen resultados en {name} para su versión actual.", "Every enabled model already has results on {name} for its current version."],
  msg_model_removed_note: ["Volverá tras la próxima búsqueda si sigue instalado; para apartarlo sin borrarlo, desactívalo.", "It is back after the next refresh if it is still installed; use model_update enabled=false to keep it out of the way instead."],
  msg_row_not_object: ["no es un objeto", "not an object"],
  msg_row_bad_json: ["JSON no válido ({detail})", "not valid JSON ({detail})"],
  msg_arena_no_pair_note: ["No hay ningún par que comparar: la arena necesita dos modelos con respuestas guardadas al mismo caso, y todos los pares ya tienen voto.", "No pair to compare: the arena needs two models with stored answers to the same case, and every pair so far has a vote."],
  msg_suite_removed_note: ["Los resultados ya medidos en sus casos siguen en el historial de las ejecuciones.", "Results already measured on its cases stay in the history of the runs."],
  msg_refresh_file_error: ["{name}: {detail}", "{name}: {detail}"],
  msg_prob_messages: ["prompt.messages: debe ser una lista de {role, content}", "prompt.messages: must be a list of {role, content}"],
  msg_prob_prompt_empty: ["prompt: vacío", "prompt: empty"],
  msg_prob_weight_positive: ["weight: debe ser positivo", "weight: must be positive"],
  msg_prob_weight_number: ["weight: debe ser un número", "weight: must be a number"],
  msg_prob_tools: ["tools: debe ser una lista de definiciones de función en el formato de herramientas de chat-completions", "tools: must be a list of function definitions in the chat-completions tools format"],
  msg_prob_checker_object: ["{path}: debe ser un objeto con un `type`", "{path}: must be an object with a `type`"],
  msg_prob_checker_checks: ["{path}: `{kind}` necesita una lista `checks` que no esté vacía", "{path}: `{kind}` needs a non-empty `checks` list"],
  msg_prob_checker_unknown: ["{path}: tipo de comprobación desconocido «{kind}» (conocidos: {options})", "{path}: unknown checker type '{kind}' (known: {options})"],

  // ------------------------------------------------------------------ notices of the Panel
  notice_title_new_model: ["Modelo nuevo: {name}", "New model: {name}"],
  notice_body_new_model: ["Mídelo para ver dónde encaja.", "Measure it to see where it fits."],
  notice_title_changed_model: ["{name} ha cambiado", "{name} changed"],
  notice_body_changed_model: ["El archivo del modelo es distinto del que se midió: los resultados anteriores están obsoletos.", "The model file is different from the one that was measured: earlier results are stale."],
  notice_title_regression: ["{name} ha empeorado", "{name} got worse"],
  notice_body_regression: ["En {n} casos compartidos puntúa {diff} menos que antes de que cambiara el modelo (p = {p}).", "On {n} shared cases it scores {diff} lower than before the model changed (p = {p})."],
  notice_title_improvement: ["{name} ha mejorado", "{name} improved"],
  notice_body_improvement: ["En {n} casos compartidos puntúa {diff} más que antes de que cambiara el modelo.", "On {n} shared cases it scores {diff} higher than before the model changed."],
  notice_title_run_failed: ["Ejecución fallida: {label}", "Run failed: {label}"],
  notice_body_run_failed: ["{error}", "{error}"],
  notice_title_not_served: ["{name} no se sirve ahora", "{name} is not served now"],
  notice_body_not_served: ["El servidor en {url} sirve {model}. Actualiza los modelos; esta entrada conserva su historial y vuelve cuando el servidor la sirva de nuevo.", "The server at {url} serves {model}. Refresh the models; this entry keeps its history and comes back when the server serves it again."],
};
